In [12]:
#TO GET ALL STATISTICAL DATA IN ONE GO
import pandas as pd
from scipy import stats

data = {'Name': ['Alice', 'John', 'Doe', 'Jane', 'Bob', 'Alice'],
        'Age': [20, 25, 30, 35, 25, 20],
        'Height': [1.75, 1.80, 1.65, 1.70, 1.80, 1.75]}
df = pd.DataFrame(data)

df.describe() #GIVES ALL STATISTICAL ANALYSIS DATA

             Age    Height
count   6.000000  6.000000
mean   25.833333  1.741667
std     5.845226  0.058452
min    20.000000  1.650000
25%    21.250000  1.712500
50%    25.000000  1.750000
75%    28.750000  1.787500
max    35.000000  1.800000

In [9]:
#STATISTICAL ANALYSIS OF CUSTOM COLUMN IN A DATAFRAME
import pandas as pd
from scipy import stats

data = {'Name': ['Alice', 'John', 'Doe', 'Jane', 'Bob', 'Alice'],
        'Age': [20, 25, 30, 35, 25, 20],
        'Height': [1.75, 1.80, 1.65, 1.70, 1.80, 1.75]}
df = pd.DataFrame(data)

# Mean
df_mean_age = df['Age'].mean()
print("Mean Age = :", df_mean_age)

# Median
df_median_height = df['Height'].median()
print("\nMedian Height:", df_median_height)

# Mode
df_mode_age = df['Age'].mode().iloc[0]  # iloc[0] is used to select the first row (mode) of the DataFrame
print("\nMode Age : ", df_mode_age)

# Variance
df_variance_age = df['Age'].var()
df_variance_height = df['Height'].var()
print("\nVariance of Age : ", df_variance_age)
print("Variance of Height : ", df_variance_height)

# Standard Deviation
df_std_age = df['Age'].std()
df_std_height = df['Height'].std()
print("\nStd Deviation of Age : ", df_std_age)
print("Std Deviation of Height : ", df_std_height)

Mean Age = : 25.833333333333332

Median Height: 1.75

Mode Age :  20

Variance of Age :  34.16666666666667
Variance of Height :  0.0034166666666666733

Std Deviation of Age :  5.845225972250061
Std Deviation of Height :  0.05845225972250066

In [13]:
#STATISTICAL ANALYSIS OF WHOLE DATAFRAME
import pandas as pd
from scipy import stats

data = {'Name': ['Alice', 'John', 'Doe', 'Jane', 'Bob', 'Alice'],
        'Age': [20, 25, 30, 35, 25, 20],
        'Height': [1.75, 1.80, 1.65, 1.70, 1.80, 1.75]}
df = pd.DataFrame(data)

# Mean
df_mean = df.mean()
print("Mean of DataFrame:")
print(df_mean)

# Median
df_median = df.median()
print("\nMedian of DataFrame:")
print(df_median)

# Mode
df_mode = df.mode().iloc[0]  # iloc[0] is used to select the first row (mode) of the DataFrame
print("\nMode of DataFrame:")
print(df_mode)

# Variance
df_variance = df.var()
print("\nVariance of DataFrame:")
print(df_variance)

# Standard Deviation
df_std_dev = df.std()
print("\nStandard deviation of DataFrame:")
print(df_std_dev)

Mean of DataFrame:
Age       25.833333
Height     1.741667
dtype: float64

Median of DataFrame:
Age       25.00
Height     1.75
dtype: float64

Mode of DataFrame:
Name      Alice
Age          20
Height     1.75
Name: 0, dtype: object

Variance of DataFrame:
Age       34.166667
Height     0.003417
dtype: float64

Standard deviation of DataFrame:
Age       5.845226
Height    0.058452
dtype: float64